name: denty
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cloud_firestore: ^3.4.3
  cupertino_icons: ^1.0.2
  date_time_picker: ^2.1.0
  firebase_auth: ^3.6.2
  firebase_core: ^1.20.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_nav_bar: ^5.0.6
  intl: ^0.17.0
  lottie: ^1.4.0
  provider: ^6.0.3
  syncfusion_flutter_datepicker: ^20.2.43

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/lottie/
    - assets/image/
    - assets/icon/png/
