// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBH10lzk9ieg3_e-Dg9etYJIOdmenwBAJ0',
    appId: '1:830757013021:web:5f6ad771d9568f32eae8f4',
    messagingSenderId: '830757013021',
    projectId: 'denty-8cfca',
    authDomain: 'denty-8cfca.firebaseapp.com',
    storageBucket: 'denty-8cfca.appspot.com',
    measurementId: 'G-EMFYMFNY2Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7V7QM93l3VEscJOvEJUJ5FQctLXTNpmw',
    appId: '1:830757013021:android:4a40a0c98628d4e3eae8f4',
    messagingSenderId: '830757013021',
    projectId: 'denty-8cfca',
    storageBucket: 'denty-8cfca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgpHw5NdHpvnFphb94OsTbRK_ITzglbjM',
    appId: '1:830757013021:ios:dee7ecd2dc32d88deae8f4',
    messagingSenderId: '830757013021',
    projectId: 'denty-8cfca',
    storageBucket: 'denty-8cfca.appspot.com',
    iosClientId: '830757013021-ous4g6ks93tsbvhhhqi48bbsgban8n5i.apps.googleusercontent.com',
    iosBundleId: 'com.example.denty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgpHw5NdHpvnFphb94OsTbRK_ITzglbjM',
    appId: '1:830757013021:ios:dee7ecd2dc32d88deae8f4',
    messagingSenderId: '830757013021',
    projectId: 'denty-8cfca',
    storageBucket: 'denty-8cfca.appspot.com',
    iosClientId: '830757013021-ous4g6ks93tsbvhhhqi48bbsgban8n5i.apps.googleusercontent.com',
    iosBundleId: 'com.example.denty',
  );
}
